### ISSUE TITLE
Design To-Do List

### ISSUE THREAD

**Issue by paulstatezny** [paulstatezny/decisive#6]
### HTML/CSS Design Tasks

Pick an item, make a pull request, put the issue # of your pull request by the item, repeat. :-)
- [x] #12 Create logo / pick "logo" font, add logo box to sidebar.
- [x] #9 Add "Grids" list to sidebar. 
- [x] #7 Add (Not) Urgent/(Not) Important headings outside of grid.
- [x] #9 Add headings to quadrants.
- [x] #9 Add item lists to quadrants. 
  - Item checkbox + text
  - "Remove Item" button
- [x] #9 Calendar icon. 
- [x] #9 Add styles for completed tasks. 
- [X] #14 Add either (1) "New Item" button OR "New Item" box.
  - The "New Item" box would replace the "New Item" button. Basically, when you hover over empty space in a quadrant, a space for a new list item would appear under the bottom one. Maybe the checkbox would appear, with text that says "click to add item" where the text would go. When you click, a text input would appear.
- [x] #13 Modify Priority and Grid headings to more closely match [prototype 2](http://invis.io/3G2OYJB5N)

**Comment by pedringt** [comment]
What still needs to be done on this issue?

**Comment by paulstatezny** [comment]
Everything that isn't checked. Although, it looks like @dmmcinty did some stuff in #8. Can you "claim" those @dmmcinty by checking the box and adding "#8" next to the items?

**Comment by dmmcinty** [comment]
It's actually issue #9 now; I deleted #8 because I created the branch incorrectly. It looks okay now. Check it out and let me know what you think!

**Comment by paulstatezny** [comment]
Nice job! I added a bunch of notes to #9 about various things. Made some adjustments and merged it.

**Comment by paulstatezny** [comment]
@pedringt The last significant thing is to add the "new item" box. I added a new screen in Invision for what that might look like.

http://invis.io/3G2OYJB5N

I'm thinking it would be a partly-opaque list item, maybe italic, basically demonstrating "Hey, if you click the mouse you'll add an item here."

I couldn't get it to do it in Sketch, but as far as that box around the text, I was thinking maybe it would be dashed instead of solid, kind of looking like the border of a coupon. (In CSS, `border-style: dashed`.)

Do you want to tackle that?

**Comment by paulstatezny** [comment]
Oh, and I just added a new item,

> Modify Priority and Grid headings to more closely match [prototype 2](http://invis.io/3G2OYJB5N)

Feel free to tackle that too!

**Comment by pedringt** [comment]
Sounds good!

**Comment by paulstatezny** [comment]
Just kidding, I did the prototype 2 stuff!

**Comment by pedringt** [comment]
Haha, no worries. Working on the New Item stuff now.
